[tox]
envlist = py{310,311,312,313,314}-{lint,mypy,unit}
source_dir = gxy_wes_bioblend
test_dir = tests

[gh-actions]
python =
    3.10: py310-unit, py310-mypy, py310-lint
    3.11: py311-unit, py311-mypy
    3.12: py312-unit, py312-mypy
    3.13: py313-unit, py313-mypy
    3.14: py314-unit, py314-mypy, py314-lint

[testenv]
commands =
    lint: isort --check --diff .
    lint: ruff check {posargs}
    lint: flake8 {posargs}
    lint: black --check --diff .
    mypy: mypy gxy_wes_bioblend
    unit: pytest {posargs}
deps =
    lint: black
    lint: flake8
    lint: flake8-bugbear
    lint: isort
    lint: ruff
    mypy: mypy
    mypy: types-requests
    unit: -rrequirements.txt
    unit: pytest
    unit: responses
skip_install =
    lint: True
